function t142_checkSize(recid){var el=$("#rec"+recid).find(".t142__submit");if(el.length){var btnheight=el.height()+5;var textheight=el[0].scrollHeight;if(btnheight<textheight){var btntext=el.text();el.addClass("t142__submit-overflowed");el.html("<span class=\"t142__text\">"+btntext+"</span>")}}}
function t235__next(){if((cur+1)>=$(".r").not('[data-t263-block-notslide=yes]').size())return;cur++;$(".r").not('[data-t263-block-notslide=yes]').each(function(i){if((cur-1)==i){var el=$(this);var trans_out_y='-100px';if(el.height()+100>$(window).height())trans_out_y='0px';el.transition({y:trans_out_y,opacity:0},250,'out',function(){el.css('display','none')})}
if(cur==i){var el=$(this);var speed='slow';if(cur==0){speed=0}
el.css('display','none');var trans_in_y='50px';if(el.height()+100>$(window).height())trans_in_y='0px';el.transition({y:trans_in_y},1,'ease',function(){});el.animate({opacity:"0"},300,function(){el.css('display','block');el.css('opacity','0');el.transition({y:'0px',opacity:1},500,'ease',function(){});$('.r').removeClass('t235__active');el.addClass('t235__active');if(typeof lazyload_cover=='object')lazyload_cover.update();if(typeof lazyload_img=='object')lazyload_img.update();if(typeof lazyload_bgimg=='object')lazyload_bgimg.update()});if(el.height()>$(window).height()){$('#t235__scrldonwicon').fadeIn('slow',function(){$('#t235__scrldonwicon').delay(1000).fadeOut('slow')})}
var bg=el.attr('data-bg-color');if(bg!==undefined&&bg!=='none'){$('#allrecordstable').css('background-color',bg)}else{$('#allrecordstable').css('background-color','')}}});t235__update();setTimeout(function(){$(window).trigger('resize');$("#allrecords").css('width',$(window).width()+'px')},400)}
function t235__prev(){if((cur-1)==-1)return;cur--;$(".r").not('[data-t263-block-notslide=yes]').each(function(i){if((cur+1)==i){var el=$(this);el.css('display','none')}
if(cur==i){var el=$(this);el.css('display','block');el.css('opacity','0');el.transition({y:'0px'},1,'easeOutSine');el.animate({opacity:"1"},50,function(){});$('.r').removeClass('t235__active');el.addClass('t235__active');var bg=el.attr('data-bg-color');if(bg!==undefined&&bg!=='none'){$('#allrecordstable').css('background-color',bg)}else{$('#allrecordstable').css('background-color','')}}});t235__update();setTimeout(function(){$(window).trigger('resize');$("#allrecords").css('width',$(window).width()+'px')},400)}
function t235__galnext(){var elactive=$('.t235__active');var tplid=elactive.attr('data-record-type');if(tplid=='5')elactive.find('[data-slide=next]').trigger('click')}
function t235__update(){var c=cur+1;var t=$(".r").not('[data-t263-block-notslide=yes]').size();$('.t235__count').html(c+'/'+t);if(typeof lazyload_cover=='object')lazyload_cover.update();if(typeof lazyload_img=='object')lazyload_img.update();if(typeof lazyload_bgimg=='object')lazyload_bgimg.update()}
function t235__init(){$("#allrecords").wrap("<table id='allrecordstable' width='100%' height='100%' style='height:100vh; border:0px; margin:0px; padding:0px; border-spacing:0px;'><tr><td></td></tr></table>");$("#allrecords").css('width',$(window).width()+'px');var wnd=$(window);$(".r").not('[data-t263-block-notslide=yes]').each(function(i){var el=$(this);el.css('padding','0px');if(el.height()>wnd.height()){el.css('padding-top','150px');el.css('padding-bottom','150px')}
el.css('display','none');el.css('opacity','');el.css('background-color','')});t235__next();$('#tildacopy').css('display','none');$('.t235').css('right','-=100');setTimeout(function(){$('.t235').addClass('t235_anim');$('.t235').css('right','+=100')},800);$(document).keydown(function(e){switch(e.which){case 38:t235__prev();break;case 40:t235__next();break;case 33:t235__prev();break;case 34:t235__next();break;case 32:t235__next();break;case 190:t235__galnext();break;default:return}
if(e.which!=190){e.preventDefault()}});$('#allrecordstable').css('transition','background-color 500ms linear');$('.t-cover__carrier').css('background-attachment','scroll')}
function t232_expandtext(recid){$("#rec"+recid).find(".t232__text").toggle()}
window.t266showvideo=function(recid){$(document).ready(function(){var el=$('#coverCarry'+recid);var videourl='';var youtubeid=$("#rec"+recid+" .t266__video-container").attr('data-content-popup-video-url-youtube');if(youtubeid>''){videourl='https://www.youtube.com/embed/'+youtubeid}
$("body").addClass("t266__overflow");$("#rec"+recid+" .t266__cover").addClass("t266__hidden");$("#rec"+recid+" .t266__video-container").removeClass("t266__hidden");$("#rec"+recid+" .t266__video-carier").html("<iframe id=\"youtubeiframe"+recid+"\" class=\"t266__iframe\" width=\"100%\" height=\"540\" src=\""+videourl+"?autoplay=1\" frameborder=\"0\" allowfullscreen></iframe><a class=\"t266__close-link\" href=\"javascript:t266hidevideo('"+recid+"');\"><div class=\"t266__close\"></div></a>")})}
window.t266hidevideo=function(recid){$(document).ready(function(){$("body").removeClass("t266__overflow");$("#rec"+recid+" .t266__cover").removeClass("t266__hidden");$("#rec"+recid+" .t266__video-container").addClass("t266__hidden");$("#rec"+recid+" .t266__video-carier").html("<div class=\"t266__video-bg2\"></div>")})}